% Auto-generated by cameraCalibrator app on 11-Oct-2021
%-------------------------------------------------------

% Define images to process
imageFileNames = {'/home/tutla/Downloads/OneDrive_2021-10-11/Data (11 Okt 21)/GOPR0162.JPG',...
    '/home/tutla/Downloads/OneDrive_2021-10-11/Data (11 Okt 21)/GOPR0163.JPG',...
    '/home/tutla/Downloads/OneDrive_2021-10-11/Data (11 Okt 21)/GOPR0164.JPG',...
    '/home/tutla/Downloads/OneDrive_2021-10-11/Data (11 Okt 21)/GOPR0165.JPG',...
    '/home/tutla/Downloads/OneDrive_2021-10-11/Data (11 Okt 21)/GOPR0166.JPG',...
    '/home/tutla/Downloads/OneDrive_2021-10-11/Data (11 Okt 21)/GOPR0167.JPG',...
    };
% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates of the corners of the squares
squareSize = 15;  % in units of 'millimeters'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
% h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
% h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
% displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);
% imshow(undistortedImage);
imwrite(undistortedImage, 'image.jpg');

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
